specVersion: 0.2.0
name: ternoa-subql-dictionary
version: 1.0.0
description: >-
  A subquery project provide dictionary data & service for a substrate-based
  network
repository: https://github.com/subquery/subql-dictionary
schema:
  file: ./schema.graphql
network:
  # genesisHash: '0xd9adfc7ea82be63ba28088d62b96e9270ad2af25c962afc393361909670835b2'
  # endpoint: wss://testnet.ternoa.com
  genesisHash: '0xd44bcfb0e98da45ace37e4df8469e5dbba8c4fc5449acda24c50cea6f5f2ca99'
  endpoint: wss://staging.chaos.ternoa.com
  # genesisHash: '0x710016a91bfbd4ffc5035ae19b7b94be74a2fd2f693cc692aaedae35c0cacd58'
  # endpoint: wss://dev.chaos.ternoa.com
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
          filter: 
            specVersion: [41, 41]
