specVersion: 0.2.0
name: ternoa-subql-dictionary
version: 1.0.0
description: >-
  A subquery project provide dictionary data & service for a substrate-based
  network
repository: https://github.com/subquery/subql-dictionary
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x6859c81ca95ef624c9dfe4dc6e3381c33e5d6509e35e147092bfbc780f777c4e'
  endpoint: wss://mainnet.ternoa.network
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler