specVersion: 1.0.0
name: Ternoa Dictionary
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: >-
  Ternoa SubQuery Dictionary project
repository: 'https://github.com/capsule-corp-ternoa/ternoa-subql-dictionary'
schema:
  file: ./schema.graphql
network:
  chainId: '0x18bcdb75a0bba577b084878db2dc2546eb21504eaad4b564bb7d47f9d02b6ace'
  endpoint: wss://alphanet.ternoa.com
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler